[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_API_BASE_URL = "https://cw-backend-xd5s.onrender.com/api/v1"
  VITE_CLOUDINARY_CLOUD_NAME = "dfg39b8ns"
  VITE_CLOUDINARY_UPLOAD_PRESET = "craftworldcentre"
  VITE_PAYMENT_PROVIDER = "paystack"
  VITE_PAYSTACK_PUBLIC_KEY = "pk_live_0904780ad18290cc231f1cb5ddee33d7937dc4de"
  VITE_SOCKET_URL = "https://cw-backend-xd5s.onrender.com"
  VITE_APP_NAME = "CraftworldCentre"
  VITE_APP_URL = "https://craftworldcentre.com"