import type { Product } from '@/types'

export const MOCK_PRODUCTS: Product[] = [
  // ─── CraftworldCentre ──────────────────────────────────────
  {
    id: 'cwc-001',
    weight: 12,
    name: 'Reclaimed Teak Coffee Table',
    slug: 'reclaimed-teak-coffee-table',
    description:
      'Hand-crafted from reclaimed teak wood salvaged from decommissioned fishing boats along the Lagos coastline. Each piece bears the unique grain and weathering of its previous life on the water. Finished with natural beeswax polish — no synthetic chemicals.',
    price: 85000,
    comparePrice: 110000,
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
      'https://images.unsplash.com/photo-1550581190-9c1c48d21d6c?w=800&q=80',
      'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=800&q=80',
    ],
    category: { id: 'furniture', name: 'Furniture', slug: 'furniture', icon: '🪑' },
    brand: {
      id: 'craftworld',
      name: 'CraftworldCentre',
      logo: '/logos/craftworld.svg',
      tagline: 'Where Waste Becomes Wonder',
      description: '',
      color: '#1A7A8A',
      accentColor: '#7BC8D8',
      focus: [],
    },
    stock: 4,
    tags: ['reclaimed', 'teak', 'furniture', 'handcrafted'],
    rating: 4.9,
    reviewCount: 38,
    isFeatured: true,
    createdAt: '2024-10-01',
  },
  {
    id: 'cwc-002',
    weight: 0.5,
    name: 'Upcycled Rope Wall Hanging',
    slug: 'upcycled-rope-wall-hanging',
    description:
      'Made from reclaimed sisal and jute rope from industrial packing materials. Each hanging is hand-knotted by artisans in Abeokuta using traditional macramé techniques. A statement piece that carries zero new resource cost.',
    price: 18500,
    images: [
      'https://images.unsplash.com/photo-1615529328331-f8917597711f?w=800&q=80',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80',
    ],
    category: { id: 'home-decor', name: 'Home Décor', slug: 'home-decor', icon: '🏡' },
    brand: {
      id: 'craftworld',
      name: 'CraftworldCentre',
      logo: '/logos/craftworld.svg',
      tagline: 'Where Waste Becomes Wonder',
      description: '',
      color: '#1A7A8A',
      accentColor: '#7BC8D8',
      focus: [],
    },
    stock: 12,
    tags: ['macramé', 'wall-art', 'home-decor', 'reclaimed-rope'],
    rating: 4.7,
    reviewCount: 22,
    isNew: true,
    createdAt: '2024-11-10',
  },
  {
    id: 'cwc-003',
    weight: 0.8,
    name: 'Recycled Glass Vase Set (3)',
    slug: 'recycled-glass-vase-set',
    description:
      'Trio of hand-blown vases crafted from recycled glass bottles collected from Lagos restaurants. Each set is unique — no two are identical. Available in Teal, Amber, and Clear.',
    price: 24000,
    comparePrice: 30000,
    images: [
      'https://images.unsplash.com/photo-1612198273689-6b8a5a3f0c80?w=800&q=80',
      'https://images.unsplash.com/photo-1501999635878-71cb5379c2d8?w=800&q=80',
    ],
    category: { id: 'home-decor', name: 'Home Décor', slug: 'home-decor', icon: '🏡' },
    brand: {
      id: 'craftworld',
      name: 'CraftworldCentre',
      logo: '/logos/craftworld.svg',
      tagline: 'Where Waste Becomes Wonder',
      description: '',
      color: '#1A7A8A',
      accentColor: '#7BC8D8',
      focus: [],
    },
    stock: 8,
    tags: ['glass', 'vase', 'home-decor', 'handblown'],
    rating: 4.8,
    reviewCount: 17,
    isFeatured: true,
    createdAt: '2024-09-15',
  },
  {
    id: 'cwc-004',
    weight: 1.2,
    name: 'Scrap Metal Desk Lamp',
    slug: 'scrap-metal-desk-lamp',
    description:
      'Industrial-chic lamp fabricated from scrap steel and copper offcuts from a Kaduna metalworks factory. LED bulb included. The imperfections in the metal are features, not flaws.',
    price: 32000,
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80',
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800&q=80',
    ],
    category: { id: 'home-decor', name: 'Home Décor', slug: 'home-decor', icon: '🏡' },
    brand: {
      id: 'craftworld',
      name: 'CraftworldCentre',
      logo: '/logos/craftworld.svg',
      tagline: 'Where Waste Becomes Wonder',
      description: '',
      color: '#1A7A8A',
      accentColor: '#7BC8D8',
      focus: [],
    },
    stock: 6,
    tags: ['lamp', 'metal', 'industrial', 'lighting'],
    rating: 4.6,
    reviewCount: 14,
    isNew: true,
    createdAt: '2024-11-20',
  },

  // ─── Adúláwò ───────────────────────────────────────────────
  {
    id: 'adl-001',
    weight: 0.5,
    name: 'Aso-oke Fragment Tote Bag',
    slug: 'asooke-fragment-tote-bag',
    description:
      'Woven from salvaged offcuts of aso-oke fabric — the premium handwoven textile used in Yoruba ceremonies. Fragments that would have been discarded are re-woven into durable, beautiful tote bags. Each bag is uniquely patterned.',
    price: 15500,
    comparePrice: 20000,
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80',
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80',
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&q=80',
    ],
    category: { id: 'fashion', name: 'Fashion', slug: 'fashion', icon: '' },
    brand: {
      id: 'adulawo',
      name: 'Adúláwò',
      logo: '/logos/adulawo.svg',
      tagline: 'Honour in Every Craft',
      description: '',
      color: '#8B6914',
      accentColor: '#d4b896',
      focus: [],
    },
    stock: 20,
    tags: ['aso-oke', 'tote', 'fashion', 'african-heritage'],
    rating: 5.0,
    reviewCount: 54,
    isFeatured: true,
    createdAt: '2024-08-05',
  },
  {
    id: 'adl-002',
    weight: 0.2,
    name: 'Brass Offcut Pendant Necklace',
    slug: 'brass-offcut-pendant-necklace',
    description:
      'Pendant cast from brass offcuts collected from a jewellery workshop in Ibadan. Each piece is unique, hand-finished, and carries the natural irregularities of the source material. A wearable piece of circular art.',
    price: 9800,
    images: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80',
      'https://images.unsplash.com/photo-1535556116002-6281ff3e9f36?w=800&q=80',
    ],
    category: { id: 'accessories', name: 'Accessories', slug: 'accessories', icon: '💍' },
    brand: {
      id: 'adulawo',
      name: 'Adúláwò',
      logo: '/logos/adulawo.svg',
      tagline: 'Honour in Every Craft',
      description: '',
      color: '#8B6914',
      accentColor: '#d4b896',
      focus: [],
    },
    stock: 30,
    tags: ['brass', 'necklace', 'jewellery', 'handcrafted'],
    rating: 4.9,
    reviewCount: 41,
    isNew: true,
    createdAt: '2024-11-01',
  },
  {
    id: 'adl-003',
    weight: 0.5,
    name: 'Indigo-Dyed Adire Cushion Cover',
    slug: 'indigo-adire-cushion-cover',
    description:
      'Traditional adire eleko (starch-resist) fabric dyed with natural indigo, made from surplus fabric ends donated by Lagos textile mills. Each piece demonstrates the resist-dye artistry of Egba Yoruba women.',
    price: 7200,
    comparePrice: 9500,
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
      'https://images.unsplash.com/photo-1558882224-dda166733046?w=800&q=80',
    ],
    category: { id: 'home-decor', name: 'Home Décor', slug: 'home-decor', icon: '🏡' },
    brand: {
      id: 'adulawo',
      name: 'Adúláwò',
      logo: '/logos/adulawo.svg',
      tagline: 'Honour in Every Craft',
      description: '',
      color: '#8B6914',
      accentColor: '#d4b896',
      focus: [],
    },
    stock: 25,
    tags: ['adire', 'cushion', 'textile', 'indigo'],
    rating: 4.8,
    reviewCount: 29,
    isFeatured: true,
    createdAt: '2024-07-20',
  },
  {
    id: 'adl-004',
    weight: 0.5,
    name: 'Leather Scrap Wallet',
    slug: 'leather-scrap-wallet',
    description:
      'Slim bifold wallet hand-stitched from quality leather offcuts salvaged from Aba shoe and bag factories. Each wallet is unique in its patchwork of leather tones. Durable, functional, and fully circular.',
    price: 11000,
    images: [
      'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80',
      'https://images.unsplash.com/photo-1591561954555-607968c989ab?w=800&q=80',
    ],
    category: { id: 'accessories', name: 'Accessories', slug: 'accessories', icon: '💍' },
    brand: {
      id: 'adulawo',
      name: 'Adúláwò',
      logo: '/logos/adulawo.svg',
      tagline: 'Honour in Every Craft',
      description: '',
      color: '#8B6914',
      accentColor: '#d4b896',
      focus: [],
    },
    stock: 18,
    tags: ['leather', 'wallet', 'accessories', 'aba'],
    rating: 4.7,
    reviewCount: 33,
    createdAt: '2024-09-10',
  },

  // ─── Planet 3R ─────────────────────────────────────────────
  {
    id: 'p3r-001',
     weight: 0.5,
    name: 'Recycled Plastic Planter Set',
    slug: 'recycled-plastic-planter-set',
    description:
      'Set of three planters moulded from post-consumer HDPE plastic — water sachets, shampoo bottles, and jerry cans collected from Lagos waste streams. UV-stabilised and weather-resistant. Perfect for indoor or outdoor use.',
    price: 13500,
    comparePrice: 17000,
    images: [
      'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80',
      'https://images.unsplash.com/photo-1463320726281-696a485928c7?w=800&q=80',
      'https://images.unsplash.com/photo-1585320806297-9794b3e4aaae?w=800&q=80',
    ],
    category: { id: 'home-decor', name: 'Home Décor', slug: 'home-decor', icon: '🏡' },
    brand: {
      id: 'planet3r',
      name: 'Planet 3R',
      logo: '/logos/planet3r.svg',
      tagline: 'Reduce. Reuse. Rethink.',
      description: '',
      color: '#3d6b2d',
      accentColor: '#a8d4a0',
      focus: [],
    },
    stock: 40,
    tags: ['plastic', 'planters', 'home', 'recycled-plastic'],
    rating: 4.8,
    reviewCount: 67,
    isFeatured: true,
    createdAt: '2024-06-15',
  },
  {
    id: 'p3r-002',
     weight: 0.5,
    name: 'Compressed Earth Block Bookends',
    slug: 'compressed-earth-bookends',
    description:
      'Bookends made from compressed laterite earth — excess soil from construction excavations. Mixed with natural binders, pressed, and cured. Weighty, beautiful, and made from material that would have been dumped.',
    price: 8900,
    images: [
      'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80',
      'https://images.unsplash.com/photo-1578898886330-87e7e7e62dba?w=800&q=80',
    ],
    category: { id: 'home-decor', name: 'Home Décor', slug: 'home-decor', icon: '🏡' },
    brand: {
      id: 'planet3r',
      name: 'Planet 3R',
      logo: '/logos/planet3r.svg',
      tagline: 'Reduce. Reuse. Rethink.',
      description: '',
      color: '#3d6b2d',
      accentColor: '#a8d4a0',
      focus: [],
    },
    stock: 15,
    tags: ['earth', 'bookends', 'home-decor', 'construction-waste'],
    rating: 4.5,
    reviewCount: 18,
    isNew: true,
    createdAt: '2024-11-05',
  },
  {
    id: 'p3r-003',
     weight: 0.5,
    name: 'Upcycled Tyre Garden Stool',
    slug: 'upcycled-tyre-garden-stool',
    description:
      'Low stool constructed from a vulcanised tyre casing stuffed with compressed recycled fabric and topped with a woven sisal seat. Durable enough for outdoor use, striking enough for indoor living.',
    price: 22000,
    comparePrice: 28000,
    images: [
      'https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800&q=80',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
    ],
    category: { id: 'furniture', name: 'Furniture', slug: 'furniture', icon: '🪑' },
    brand: {
      id: 'planet3r',
      name: 'Planet 3R',
      logo: '/logos/planet3r.svg',
      tagline: 'Reduce. Reuse. Rethink.',
      description: '',
      color: '#3d6b2d',
      accentColor: '#a8d4a0',
      focus: [],
    },
    stock: 7,
    tags: ['tyre', 'stool', 'furniture', 'upcycled'],
    rating: 4.9,
    reviewCount: 25,
    isFeatured: true,
    createdAt: '2024-08-22',
  },
  {
    id: 'p3r-004',
     weight: 0.5,
    name: 'Recycled Paper Stationery Set',
    slug: 'recycled-paper-stationery-set',
    description:
      'Notebook, notepad, and pen made entirely from recycled office paper collected from Lagos corporate offices. The paper has natural flecks that give it a warm, organic texture. Pen barrel crafted from a recycled aluminium tube.',
    price: 6500,
    images: [
      'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800&q=80',
      'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&q=80',
    ],
    category: { id: 'stationery', name: 'Stationery', slug: 'stationery', icon: '�' },
    brand: {
      id: 'planet3r',
      name: 'Planet 3R',
      logo: '/logos/planet3r.svg',
      tagline: 'Reduce. Reuse. Rethink.',
      description: '',
      color: '#3d6b2d',
      accentColor: '#a8d4a0',
      focus: [],
    },
    stock: 50,
    tags: ['stationery', 'paper', 'recycled', 'notebook'],
    rating: 4.6,
    reviewCount: 45,
    isNew: true,
    createdAt: '2024-10-30',
  },
  {
    id: 'p3r-005',
     weight: 0.5,
    name: 'Shredded Plastic Doormat',
    slug: 'shredded-plastic-doormat',
    description:
      'Heavy-duty doormat woven from shredded post-consumer PET plastic bottles. Waterproof, fade-resistant, and scrub-friendly. Every mat keeps approximately 80 plastic bottles out of the environment.',
    price: 9200,
    comparePrice: 12000,
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
      'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&q=80',
    ],
    category: { id: 'home-decor', name: 'Home Décor', slug: 'home-decor', icon: '🏡' },
    brand: {
      id: 'planet3r',
      name: 'Planet 3R',
      logo: '/logos/planet3r.svg',
      tagline: 'Reduce. Reuse. Rethink.',
      description: '',
      color: '#3d6b2d',
      accentColor: '#a8d4a0',
      focus: [],
    },
    stock: 35,
    tags: ['doormat', 'plastic-bottles', 'home', 'pet'],
    rating: 4.7,
    reviewCount: 52,
    isFeatured: true,
    createdAt: '2024-07-01',
  },
  {
    id: 'cwc-005',
     weight: 0.5,
    name: 'Denim Patchwork Throw Blanket',
    slug: 'denim-patchwork-throw-blanket',
    description:
      'Cozy throw blanket hand-sewn from denim offcuts and worn jeans donated to our fabric recovery programme. Each blanket is a wearable narrative of garments that came before — unique and warm.',
    price: 19500,
    images: [
      'https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?w=800&q=80',
      'https://images.unsplash.com/photo-1599640842225-85d111c60e6b?w=800&q=80',
    ],
    category: { id: 'home-decor', name: 'Home Décor', slug: 'home-decor', icon: '🏡' },
    brand: {
      id: 'craftworld',
      name: 'CraftworldCentre',
      logo: '/logos/craftworld.svg',
      tagline: 'Where Waste Becomes Wonder',
      description: '',
      color: '#1A7A8A',
      accentColor: '#7BC8D8',
      focus: [],
    },
    stock: 9,
    tags: ['denim', 'blanket', 'patchwork', 'fabric-recovery'],
    rating: 4.8,
    reviewCount: 31,
    isNew: true,
    createdAt: '2024-11-15',
  },
  {
    id: 'adl-005',
     weight: 0.5,
    name: 'Ankara Fabric Earrings',
    slug: 'ankara-fabric-earrings',
    description:
      'Lightweight statement earrings made from ankara print fabric offcuts, stiffened with natural cassava starch and finished with brass wire hooks salvaged from electronic waste. Bold, cultural, circular.',
    price: 4500,
    images: [
      'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&q=80',
      'https://images.unsplash.com/photo-1589128777073-263566ae5e4d?w=800&q=80',
    ],
    category: { id: 'accessories', name: 'Accessories', slug: 'accessories', icon: '💍' },
    brand: {
      id: 'adulawo',
      name: 'Adúláwò',
      logo: '/logos/adulawo.svg',
      tagline: 'Honour in Every Craft',
      description: '',
      color: '#8B6914',
      accentColor: '#d4b896',
      focus: [],
    },
    stock: 45,
    tags: ['ankara', 'earrings', 'jewellery', 'african-print'],
    rating: 4.9,
    reviewCount: 88,
    isFeatured: true,
    isNew: true,
    createdAt: '2024-11-22',
  },
]

export const getProductsByBrand = (brandId: string) =>
  MOCK_PRODUCTS.filter((p) => p.brand.id === brandId)

export const getProductsByCategory = (categoryId: string) =>
  MOCK_PRODUCTS.filter((p) => p.category.id === categoryId)

export const getFeaturedProducts = () =>
  MOCK_PRODUCTS.filter((p) => p.isFeatured)

export const getNewProducts = () =>
  MOCK_PRODUCTS.filter((p) => p.isNew)

export const getProductBySlug = (slug: string) =>
  MOCK_PRODUCTS.find((p) => p.slug === slug)

export const formatPrice = (amount: number): string =>
  `₦${amount.toLocaleString('en-NG')}`
